apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-event-producer-api
  name: location-event-producer-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: location-event-producer-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-event-producer-api
  name: location-event-producer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-event-producer-api
  template:
    metadata:
      labels:
        service: location-event-producer-api
    spec:
      containers:
      - image: goleng/location-service-api:latest
        name: location-event-producer-api
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always